"noDZy9bG2RkUAqPOWcQLwtFYh0nkaYSIG4NnA6KTl0cQVfVSu0oK66MNuMS3kqaU"
['SOLUSDTPERP', 'BTCUSDTPERP', 'ETHUSDTPERP', 'ADAUSDTPERP', 'FTMUSDTPERP', 'APTUSDTPERP', 'ATOMUSDTPERP', 'APEUSDTPERP', 'ENSUSDTPERP', 'XRPUSDTPERP', 'SNXUSDTPERP', 'BCHUSDTPERP', 'BNBUSDTPERP', 'DOTUSDTPERP', 'MASKUSDTPERP']
['5m', '15m', '30m', '1h', '4h']
